import Navbar from '@/components/Navbar'
import './globals.css'
import { Inter } from 'next/font/google'
import getCurrentUser from '@/app/actions/getCurrentUser'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}
// SessionProvider 를지우고 클라이언트 컴포넌트 -> 서버 컴포넌트로 변경
// 서버 컴포넌트 > 메타데이터, async 사용
export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const currentUser = await getCurrentUser()

  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar currentUser={currentUser} />
        {children}
      </body>
    </html>
  )
}
